### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [blochberger/Tafelsalz#10]
Hi @blochberger, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by blochberger** [comment]
Hi @samuel-lucas6. I am currently not pursuing development due to other things on my plate, being the only maintainer/developer, and I am not aware of anybody using the library (so no external pressure for me to prioritize the work). However, I still plan on continuing development and are available for questions etc.

If this library gets removed, it can always be added once development actually continues ;)

**Comment by samuel-lucas6** [comment]
Thanks for getting back to me. Yep, you can always add it back :)
